### PR TITLE
Add alternative syntax section to README.md

### PR DESCRIPTION
**Pull request by nickburris**
Add a section on alternative syntax per issue #15.

### CODE REVIEW

**Comment by yoavweiss** [comment]
@nickburris - can you join the WICG and link your GH account with your W3C one to appease the IPR bots?

**Comment by nickburris** [comment]
> @nickburris - can you join the WICG and link your GH account with your W3C one to appease the IPR bots?

Done! (was pending group approval)

@bokand PTAL

**Comment by bokand** [comment]
I think this might a be a bit confusing, a reader could reasonably read this as proposing that either syntax could be accepted. Could we instead update the README to use the new ## syntax?

**Comment by bokand** [comment]
With a caveat that this extension to the URL spec is an open question.

**Comment by nickburris** [comment]
> I think this might a be a bit confusing, a reader could reasonably read this as proposing that either syntax could be accepted. Could we instead update the README to use the new ## syntax?

Done.

**Comment by bokand** [comment]
lgtm, thanks.

**Pull request merged**
